### ISSUE TITLE
LayoutView.render/2 is undefined after json Response

### ISSUE THREAD

**Issue by TheYuwana** [andreapavoni/plug_ets_cache#1]
Hey guys, this issue does not break the app but I do keep getting a LayoutView.render/2 is undefined error when I do the following:

> def get_stuff(conn, _params) do
    stuff = Context.list_stuff()
    conn
    |> put_status(200)
    |> render(StuffView, "stuff.json", stuff: stuff)
    |> cache_response
  end

or

> def get_stuff(conn, _params) do
    conn
          |> put_status(200)
          |> json(%{status: "succes", message: "stuff"})
          |> cache_response
  end

Followed the simple steps given in the docs.. Any opinions on this?

**Comment by andreapavoni** [comment]
Hi there!

Thanks for opening this issue. To be honest, I've tried/tested with html, xml amd txt formats without problems. I'll check your case as soon as possible ;-)

**Comment by andreapavoni** [comment]
I'm still away from PC, however, just in case, have you tried to put this in your controller?

```
plug :put_layout, false
```

This *should/might* solve the error. I'll dig deeper once I put my hands on a keyboard ;-)

**Comment by TheYuwana** [comment]
No problem man! Weekend is over and also started to touch the keyboard again! Alright I've set the put_layout on on false and the error is gone. Thanks!

**Comment by joshuataylor** [comment]
Was also running into this in my Phoenix API (doesn't use HTML, just JSON responses)), putting:
```
plug :put_layout, false
```
Inside of my `router.ex` in the scope fixed it.

Thanks!
